### ISSUE TITLE
[ERROR] table content empty, file not written and Expected value but found T_END at character 1

### ISSUE THREAD

**Issue by mamscience** [equiposinoficina/notion-proxy-ng#5]
Hi there

Thanks for this project. I'm unfortunately stuck at the slug phase.
Following your instructions, I made a database with contains pages. Unfortunately, when running ./run.sh, it returns this error: 
```
[ERROR] table content empty, file not written. 
```
I followed the instructions and added property, but still the same results prevail.

And also, when I thought slugs were optional, but the docker container keeps restarting due to the following error
```	[C]: in function 'decode'
	/notion-proxy-ng/modules/get_cache.lua:11: in main chunk
nginx: [error] init_by_lua_file error: /notion-proxy-ng/modules/get_cache.lua:11: Expected value but found T_END at character 1```

**Comment by mamscience** [comment]
just retried everything from the start, and now everything seems to be fine without slugs

However, please update the slugs section, it's not very clear what has to be done with the database. 

BR

**Comment by oriolrius** [comment]
Sorry, but the project is discontinued and maybe not compatible with 
Notion any more.  So, I don' give support of the code.




------ Original Message ------
From "mamscience" ***@***.***>
To "equiposinoficina/notion-proxy-ng" 
***@***.***>
Cc "Subscribed" ***@***.***>
Date 27/02/2024 20:16:41
Subject [equiposinoficina/notion-proxy-ng] [ERROR] table content empty, 
file not written and Expected value but found T_END at character 1 
(Issue #5)
